[package]
name = "rust-port"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.17", features = ["derive", "wrap_help"] }
tokio = { version = "1.40.0", features = ["full", "rt-multi-thread"] }
